name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Har kuni yaratiladi
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: Nod1rbe
          outputs: dist/snake.svg

      - name: Push the animation
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
