name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Har kuni yaratiladi
  workflow_dispatch: # Qo'lda ishga tushirish imkonini beradi

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Nod1rbe
          outputs: dist/snake.svg

      - name: Upload Snake
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/snake.svg
